# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-05-21 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='swiperd',
            unique_together=set([('uid', 'sid')]),
        ),
    ]
