# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-05-25 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vip_end',
            field=models.DateTimeField(default='2022-02-22', verbose_name='会员过期时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='vip_id',
            field=models.IntegerField(default=1, verbose_name='用户对应的会员ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dating_gender',
            field=models.CharField(choices=[('male', '男性'), ('female', '女性')], default='female', max_length=10, verbose_name='匹配的性别'),
        ),
    ]
